### ISSUE TITLE
버그잡기 - 스토커가 뒤돌아 봤을 때 스토커 숨는 스피드 조정

### ISSUE THREAD

**Issue by jiyeonshin** [Yejuroo/Stalker#49]

**Comment by Arkhtyi** [comment]
스토커 상태를 함수로 뺴두기
1. 기본(default) - 그냥 달려오기
2. 들킴(detected) - 들켜서 달려오기
3. 멈춤(static) - 플레이어가 안전지대로 들어 갔을 때 스토커가 멈추는 것(은폐 오브젝트에 숨어있음)
4. 가속(acc) - 행인과의 접선 실패 등의 이유로 스토커가 움직임이 빨라짐
5. 감속(decc) - 아이템 사용 등의 이유로 스토커가 쫄아서 움직임이 느려짐
